import PDFDocument from "pdfkit";

interface PdfData {
  title: string;
  businessName: string;
  industry: string;
  overallScore: number;
  scores: { label: string; score: number }[];
  rootCause: string;
  findings: { category: string; title: string; severity: string; detail: string }[];
}

export async function generatePdfReport(data: PdfData): Promise<Buffer> {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    // Header
    doc.fontSize(24).font("Helvetica-Bold").text("Tasknator", { align: "center" });
    doc.fontSize(10).font("Helvetica").fillColor("#6b7280").text("AI Business Diagnostics Report", { align: "center" });
    doc.moveDown(2);

    // Business info
    doc.fontSize(18).font("Helvetica-Bold").fillColor("#111827").text(data.title);
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica").fillColor("#374151");
    doc.text(`Business: ${data.businessName}`);
    doc.text(`Industry: ${data.industry}`);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`);
    doc.moveDown(1);

    // Overall score
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Overall Score");
    doc.fontSize(36).font("Helvetica-Bold");
    const scoreColor = data.overallScore >= 70 ? "#22c55e" : data.overallScore >= 40 ? "#f59e0b" : "#ef4444";
    doc.fillColor(scoreColor).text(`${data.overallScore}/100`);
    doc.moveDown(1);

    // Scores
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Score Breakdown");
    doc.moveDown(0.5);
    for (const score of data.scores) {
      doc.fontSize(10).font("Helvetica").fillColor("#374151");
      doc.text(`${score.label}: ${score.score}/100`);
    }
    doc.moveDown(1);

    // Root cause
    if (data.rootCause) {
      doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Root Cause Analysis");
      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica").fillColor("#374151").text(data.rootCause);
      doc.moveDown(1);
    }

    // Findings
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Findings");
    doc.moveDown(0.5);
    for (const finding of data.findings) {
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#111827");
      doc.text(`[${finding.severity}] ${finding.title}`);
      doc.fontSize(9).font("Helvetica").fillColor("#6b7280");
      doc.text(`Category: ${finding.category}`);
      doc.fontSize(9).font("Helvetica").fillColor("#374151");
      doc.text(finding.detail);
      doc.moveDown(0.5);
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).font("Helvetica").fillColor("#9ca3af");
    doc.text("Generated by Tasknator - AI that fixes business bottlenecks", { align: "center" });

    doc.end();
  });
}
